coverage_service: cobertura_xml
xcodeproj: MapillarySDK/MapillarySDK.xcodeproj
workspace: MapillarySDK/MapillarySDK.xcworkspace
scheme: Test
source_directory: MapillarySDK/MapillarySDK
output_directory: /cobertura
ignore:
  - MapillarySDK/Pods/*

