platform :ios, '8.0'
#use_frameworks!

target 'MapillarySDK' do

    pod 'AFNetworking', '~> 3.1'
    pod 'BOSImageResizeOperation', '~> 0.1'
    pod 'OCMockito', '~> 5.0'
    pod 'SDVersion', '~> 4.0'
    pod 'AWSCore', '~> 2.6'
    pod 'AWSS3', '~> 2.6'

    target 'MapillarySDKTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
