platform :ios, '8.0'
#use_frameworks!

target 'MapillarySDK' do

    pod 'BOSImageResizeOperation'

    target 'MapillarySDKTests' do
        inherit! :search_paths
        # Pods for testing
    end

end
