#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$(dirname "$current_dir")"

echo "HELLO"

pwd
ls

cd $PARENT_DIR/MapillarySDK

echo "Building..."

xcodebuild -workspace $PARENT_DIR/MapillarySDK/MapillarySDK.xcworkspace \
           -scheme MapillarySDK \
           -configuration Debug \
           -destination 'platform=iOS Simulator,OS=11.0.1,name=iPhone 6' \
           -derivedDataPath "build" \
           build-for-testing
