#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARRENT_DIR="$(dirname "$current_dir")"

echo "HELLO"

cd $CURRENT_DIR/../MapillarySDK

echo "Building..."

xcodebuild -workspace MapillarySDK.xcworkspace \
           -scheme MapillarySDK \
           -configuration Debug \
           -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 6' \
           -derivedDataPath "build" \
           build-for-testing