#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$(dirname "$CURRENT_DIR")"

cd MapillarySDK

echo "Generating workspace"
export LANG=en_US.UTF-8
/usr/local/bin/pod install

echo "Building..."
xcodebuild -workspace MapillarySDK.xcworkspace \
           -scheme Test \
           -configuration Debug \
           -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 6' \
           build-for-testing