#!/bin/bash

OUTPUT="../licenses.csv"
PLIST=../MapillarySDK/Pods/Target\ Support\ Files/Pods-MapillarySDK/Pods-MapillarySDK-acknowledgements.plist

rm -rf $OUTPUT
FILE="temp.plist"
cp "$PLIST" $FILE

count=$(/usr/libexec/PlistBuddy -c "print :PreferenceSpecifiers:" $FILE | grep "Dict"|wc -l)

for i in `seq 1 $(expr $count - 2)`; do
    declare -a lib=$(/usr/libexec/PlistBuddy -c "print :PreferenceSpecifiers:$i:Title" $FILE)
    declare -a lic=$(/usr/libexec/PlistBuddy -c "print :PreferenceSpecifiers:$i:License" $FILE)
            
    echo $lib, unknown, \"$lic\" >> $OUTPUT
done

rm $FILE