#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$(dirname "$current_dir")"

echo "Setting up..."

sudo gem install cocoapods
sudo gem install slather
sudo gem install ocunit2junit