#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$(dirname "$current_dir")"

echo "Setting up..."

gem install cocoapods --user-install
gem install slather --user-install
gem install ocunit2junit --user-install