#!/bin/bash
export LANG=en_US.UTF-8

pod update --project-directory=MapillarySDK/
xcodebuild -workspace MapillarySDK/MapillarySDK.xcworkspace/ -scheme MapillarySDK

echo "Running tests..."
set -o pipefail && xcodebuild test \
           -workspace MapillarySDK/MapillarySDK.xcworkspace \
           -scheme MapillarySDK \
           -configuration Debug \
           -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' 2>&1 | /usr/local/bin/ocunit2junit 

RC=$?

echo "Collecting code coverage..."
/usr/local/bin/slather

echo "Copying reports..."
mkdir -p test_results/unit
mkdir -p test_results/cobertura
cp -a test-reports/. test_results/unit/
cp -a cobertura/cobertura.xml test_results/cobertura/coverage.xml
rm -rf test-reports
rm -rf cobertura

exit $RC
