#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARRENT_DIR="$(dirname "$current_dir")"

cd MapillarySDK

echo "Running tests..."
xcodebuild test-without-building \
           -workspace MapillarySDK.xcworkspace \
           -scheme Test \
           -destination 'platform=iOS Simulator,OS=11.0.1,name=iPhone 6' 2>&1 | /usr/local/bin/ocunit2junit

echo "Collecting code coverage..."
/usr/local/bin/slather coverage --cobertura-xml --scheme Test --output-directory ./cobertura/ --workspace ./MapillarySDK.xcworkspace ./MapillarySDK.xcodeproj

echo "Copying reports..."
mkdir -p ~/test-reports/unit
mkdir -p ~/test-reports/cobertura
cp -a test-reports/. ~/test-reports/unit/
cp -a cobertura/cobertura.xml ~/test-reports/cobertura/cobertura.xml
echo "DONE."

cd ..

#exit 0
